name: Sync Fork

on:
  workflow_dispatch: # on button click
  schedule:
    - cron: '*/5 * * * *' # every 30 minutes
jobs:
  sync_and_build:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: elyeandre
          base: main
          head: main
